FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD springhiberantajpa.jar /opt/springhiberantajpa/
EXPOSE 8080
WORKDIR /opt/springhiberantajpa/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "springhiberantajpa.jar"]
